#!/bin/sh
# Disattiva lo swap attuale
swapoff /dev/zram0 2>/dev/null
# Reset del device ZRAM
echo 1 > /sys/block/zram0/reset
# Imposta algoritmo di compressione (trascurabile)
echo lz4 > /sys/block/zram0/comp_algorithm
# Imposta dimensione ZRAM (4 GB)
echo 4294967296 > /sys/block/zram0/disksize
# Ricrea lo swap
mkswap /dev/zram0
# Attiva lo swap con priorità 5
swapon /dev/zram0 -p 5
# Imposta swappiness finale
sysctl -w vm.swappiness=20